GET http://localhost:1111/api/rooms


###

POST http://localhost:1111/api/rooms/new
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "Red Room",
  "file_name": "123.png"
}

###
DELETE http://localhost:9999/api/rooms/1


###
POST http://localhost:9999/api/rooms/lock/2

###
POST http://localhost:9999/api/rooms/unlock/1

###
GET http://localhost:9999/api/rooms/unlock

###
GET http://localhost:9999/api/rooms/locked

###

POST http://localhost:1111/api/rooms/history/0
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "room_id": 1,
  "user_login": "admin",
  "name_meeting": "Митинг",
  "start_time": 0,
  "end_time": 1
}

###
GET http://localhost:1111/api/rooms/history


###
GET http://localhost:1111/api/rooms/history/1


###
POST http://localhost:1111/api/rooms/history/add/result/1
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "result": "Что-то случилось"
}

###

GET http://localhost:1111/api/history/room/1

###

